name: Cross-Platform Build


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: ./pyinstaller/windows.spec
        requirements: ./requirements.txt
        path: ./src

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: ./dist/windows
